---
title: "Projekt egzaminacyjny"
author: "Antonina Brzeska"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(evir)
library(tidyverse)
library(ismev)
library(ggplot2)
library(tidyverse)
```



```{r}

#WCZYTYWANIE DANYCH
#path_loc <- "C:/repo/ModZdEkstr/Analiza02"
path_loc <- "H:/Repo/ModZdEkstr/Analiza02"
setwd(path_loc)

df <- read_csv("waves20months-ok.csv") ; df

#PODGLĄD DANYCH
glimpse(df)

#UPEWNIENIE, ŻE DANE SĄ TYPU NUMERYCZNEGO
df$Hmax <- as.numeric(df$Hmax)

#WCZYTANIE DANYCH Z KOLUMNY WYSOKOŚCI FAL
data <- df$Hmax

#KWANTYL 90%
u=quantile(data,0.99); u # u 90% = 3.29 ; u 99% = 4.75188

```

```{r}
######################################################## METODA MAKSIMÓW BLOKOWYCH BMM

#2. Analiza metodą maksimów blokowych (BMM). Wyestymowano parametry
#rozkładu GEV w oparciu o maksima z ustalonych bloków 20-stu miesięcy:

fitGEV=evir::gev(data,30*47); 
fitGEV$par.ests #- wyestymowane parametry xi sigma mu
xiGEV=fitGEV$par.ests[[1]]; xiGEV
sigmaGEV=fitGEV$par.ests[[2]]; sigmaGEV
muGEV=fitGEV$par.ests[[3]]; muGEV

#xi      sigma         mu 
#-0.3372591  1.0874319  4.5626598
#fitGEV
```


```{r}
#Przeprowadzono analizę oceniającą dobroć dopasowania za pomocą następujących
#wykresów diagnostycznych (METODA MAKSIMÓW BLOKOWYCH BMM):

fitt.X <- fExtremes::gevFit(data,20)
summary(fitt.X)

```

```{r}
#POZIOM ZWROTU k20 METODĄ MAKSIMÓW BLOKOWYCH
fExtremes::gevrlevelPlot(fitt.X,20)
evir::rlevel.gev(fitGEV, k.blocks = 20) #6.602865

```
```{r}
############################################# METODA PRZEKROCZEŃ PROGU POT
#3. Analiza metodą przekroczeń progu (POT)

#KWANTYL 90%
u=quantile(data,0.99); u
#u=quantile(data, 1-1/(10*30*47)); u

#estymujemy parametry rozkladu GPD
#gpd(dane,u) - podajemy prog lub liczbe nadwyzek
fitGPD=ismev::gpd.fit(data,u)   #u=kwantyl 90%, 
#można podać liczbę nadwyżek, tutaj 0.10*length(data)

#wyestymowane parametry rozkladu GPD
xi=fitGPD$mle[[2]]; xi
beta=fitGPD$mle[[1]]; beta

#[1] -0.1663637 xi
#[1] 0.7715406 beta

```

```{r}
######################################################## METODA PRZEKROCZEŃ PROGU POT
#wykresy ROZRZUTU z zaznaczonym progiem u=kwantyl 99%
plot(data)
abline(h=u,lwd=3,col='red')   

#oraz wykres nadwyzek nad prog u=kwantyl 99%
Y=data[data>u]
plot(Y,type='h')

```

```{r}
######################################################## METODA PRZEKROCZEŃ PROGU POT
#dobroć dopasowania  na wykresach 
ismev::gpd.diag(fitGPD)

```

```{r}
# METODA POT PRZEKROCZEŃ PROGU
#Nu=length(Y)   #licznosc nadwyzek
#N=length(data)    #licznosc probki

fitRm= gpd(data,u)
k20 = 1-1/(20*30*47) #poziom zwrotu k20 30 dni w bloku i 47 rekordów /dzień
riskmeasures(fitRm,k20)[2] #6.689767
```


```{r}
################################################ METODA BOOTSTRAPOWA
#KWANTYL
u=quantile(data,0.95); u # kwantyl 95% = 3.8

#srednia 2.038678, mediana 1.85
mean(data); median(data)

#generujemy 10000 prob bootstrapowych i obliczamy ŚREDNIĄ puli danych
Db=c()
for(i in 1:1000){
  Y=sample(data,28,replace=TRUE)
  Db[i]=median(Y)
}
alpha <- quantile(Db, 1-1/(20)); alpha #2.20525

hist(Db,prob=T)
abline(v=alpha, col=2)

#generujemy 10000 prob bootstrapowych i obliczamy MEDIANĘ puli danych
Db=c()
for(i in 1:1000){
  Y=sample(data,28,replace=TRUE)
  Db[i]=mean(Y)
}
alpha <- quantile(Db, 1-1/(20)); alpha #2.322766

hist(Db,prob=T)
abline(v=alpha, col=2)

#generujemy 10000 prob bootstrapowych i obliczamy MAX puli danych
Db=c()
for(i in 1:1000){
  Y=sample(data,28,replace=TRUE)
  Db[i]=max(Y)
}
alpha <- quantile(Db, 1-1/(20)); alpha #5.615

hist(Db,prob=T)
abline(v=alpha, col=2)

```

```{r}
####################################################### BACKTESTING

logz=-diff(log(data))   #minus log-zwroty
head(logz)

#Ustalamy "okno" licznosci 1000 i estymujemy kolejne kwantyle trzema metodami (500 przejść pętli)

#Metoda 1 (historyczna)
Metoda1=c()  
for (i in 1:1500) { #27100
  j=i+999
  X = logz[i:j]
  Metoda1[i]=quantile(X, 0.95)#(1-1/(20*30*47)))
}

#Metoda 2 - bootstrap (MAX)
Metoda2=c()         
for (i in 1:1500) { #748
  j=i+999
  X = logz[i:j]
  Db=c()
  for(a in 1:99){
    Y=sample(X,10,replace=TRUE)
    Db[a]=max(Y)
  }
  Metoda2[i] <- quantile(Db, 0.95);
}

#Metoda 5 - bootstrap (ŚREDNIA)
Metoda5=c()         
for (i in 1:1500) {
  j=i+999
  X = logz[i:j]
  Db=c()
  for(a in 1:99){
    Y=sample(X,10,replace=TRUE)
    Db[a]=mean(Y)
  }
  Metoda5[i] <- quantile(Db, 0.95);
}

#Metoda 3 - POT
Metoda3=c()         
for (i in 1:1500) {
  j=i+999
  X = logz[i:j]
  u=quantile(X,0.95)
  fitGPD=gpd(X,u)
  xi=fitGPD$par.est[[1]]
  beta=fitGPD$par.est[[2]]
  Nu=length(X[X>u])   #licznosc nadwyzek
  N=length(X)
  Metoda3[i]=u+((20*Nu/N)^xi-1)*beta/xi
}

#Metoda 4 - metoda przekroczeń progu
Metoda4=c()         
for (i in 1:1500) {
  j=i+999
  X = logz[i:j]
  
  fit=evir::gev(X,49); 
  Metoda4[i] = evir::rlevel.gev(fit, k.blocks = 20)[2] ; Metoda4[i]
}

```
```{r}

#porownanie estymacji na wykresie
par(mfrow = c(1, 1))
plot(-logz[1001:1500],type='l',lwd=2, xlab=NA,ylab=NA) #28100
points(-Metoda2,type='l',col='blue', lwd=2)
points(-Metoda4,type='l',col='yellow', lwd=2)
points(-Metoda1,type='p',col='red', lwd=2)
points(-Metoda3,type='l',col='green', lwd=2)
points(-Metoda5,type='l',col='orange', lwd=2)

#legend(50, -0.06, c("historyczna", "bootstrapowa f()=max()","bootstrapowa #f()=średnia()", "POT", "Maksima blokowe"), 
#       col = c('red','blue','orange', 'green', 'yellow'),
#       text.col = "green4", lty = c(1, 1, 1, 1), 
#       bg = "gray90")

#ile procent stop przekroczylo wyestymowany tymi metodami prog.
R1=logz[1001:1500]  #kolejne stopy z pominieciem 1000 pierwszych #28100
L1 <- sapply(R1 > Metoda1, as.integer) #1 - gdy stopa przekroczy prog
L2 <- sapply(R1 > Metoda2, as.integer) #0 - gdy stopa nie przekroczy progu
L3 <- sapply(R1 > Metoda3, as.integer) 
L4 <- sapply(R1 > Metoda4, as.integer) 
L5 <- sapply(R1 > Metoda5, as.integer) 

head(L1); head(L2); head(L3); head(L4); head(L5)

#procent jedynek, czyli przekroczen
p1=100*sum(L1)/length(R1)
p2=100*sum(L2)/length(R1)
p3=100*sum(L3)/length(R1)
p4=100*sum(L4)/length(R1)
p5=100*sum(L5)/length(R1)


round(p1,2); round(p2,2); round(p3,2); round(p4,2); round(p5,2)

```
